kind: PersistentVolume
apiVersion: v1
metadata: 
  name: mongo-pv
  labels:
    app: local
  namespace: chat-app
spec:
  capacity: 
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage
  hostPath:
    path: /data/db
 
